# Generated by Django 4.2.30 on 2026-07-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_add_is_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_borrowed', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('borrow_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrow_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=30)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_count', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('is_borrowable', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('type_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type_label', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'item_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimsUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=150, unique=True)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('lab_personnel', 'Lab Personnel'), ('it_personnel', 'IT Personnel')], max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=120)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('room_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Lab Personnel', 'Lab Personnel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student_teacher', 'Student / Teacher'), ('lab_personnel', 'Lab Personnel'), ('it_personnel', 'IT Personnel')], default='student_teacher', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
